#端口号
server.port=8899

#根路径
server.servlet.context-path=/app

#项目名称
spring.application.name=test-service

#es配置
spring.elasticsearch.rest.uris=127.0.0.1:9200
spring.elasticsearch.rest.connectionTimeout=3
spring.elasticsearch.rest.readTimeout=90
spring.elasticsearch.rest.username=
spring.elasticsearch.rest.password=

#线程池
async.executor.thread.core_pool_size=1
async.executor.thread.max_pool_size=2
async.executor.thread.queue_capacity=512

#数据库配置
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.druid.url=jdbc:mysql://172.18.1.156:3306/uat_partner?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&failOverReadOnly=false
spring.datasource.druid.username=partner
spring.datasource.druid.password=983!SUN@#9020@809

# 初始化⼤⼩、最⼩、最⼤连接数
spring.datasource.druid.initial-size=3
spring.datasource.druid.min-idle=3
spring.datasource.druid.max-active=10

# 配置获取连接等待超时的时间
spring.datasource.druid.max-wait=60000

# 监控后台账号和密码
spring.datasource.druid.stat-view-servlet.enabled=true
spring.datasource.druid.stat-view-servlet.login-username=admin
spring.datasource.druid.stat-view-servlet.login-password=admin
spring.datasource.druid.stat-view-servlet.reset-enable=false

# 配置 StatFilter
spring.datasource.druid.filter.stat.log-slow-sql=true
spring.datasource.druid.filter.stat.slow-sql-millis=2000

mybatis.typeAliasesPackage=com.example.testapi.model
mybatis.mapperLocations=classpath*:/mapper/**/**Mapper.xml